version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/docker/:/config
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
      - ./config/ssl/:/etc/letsencrypt/live/leads1llc.com/
    command: [sh, '/config/startup.sh']
    networks:
      app:
        ipv4_address: 10.6.0.2

  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_HOST: '${DATABASE_HOST}'
      MYSQL_TCP_PORT: '${DATABASE_PORT}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DATABASE_USERNAME}", "-p${DATABASE_PASSWORD}", "-h${DATABASE_HOST}", "-P${DATABASE_PORT}", "ping"]
      retries: 3
      timeout: 5s
    networks:
      app:
        ipv4_address: 10.6.0.3

  web:
    build: ./packages/web
    volumes:
      - ./packages/web:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      app:
        ipv4_address: 10.6.0.4

  core:
    build: ./packages/core
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    ports:
      - 1337:1337
    volumes:
      - ./packages/core:/app
    env_file:
      - .env

    networks:
      app:
        ipv4_address: 10.6.0.5

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
